#!/bin/bash
FILE=discordiador
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --log-file="cfg/valgrind_discordiador.log" --show-reachable=no --num-callers=20 ./$FILE
fi