#!/bin/bash
FILE=mi-ram-hq
make $FILE
if test -f "./$FILE"; then
    valgrind --tool=memcheck --track-origins=yes --leak-check=full --show-leak-kinds=all --show-possibly-lost=no --show-reachable=yes --num-callers=20 --log-file="cfg/valgrind.log" ./$FILE cfg/mi-ram-hq.config cfg/mi-ram-hq.log
fi